services:
  - type: web
    name: solar-sms-survey
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10